# Main Window frame
MAIN_WINDOW_POSITION_X = 300
MAIN_WINDOW_POSITION_Y = 300
MAIN_WINDOW_LENGTH = 800
MAIN_WINDOW_WIDTH = 450
SPACING = 0
# Workout list display
WORKOUT_PER_LINE = 3
WORKOUT_BUTTON_LENGTH_CELL = 2
WORKOUT_BUTTON_WIDTH_CELL = 2
